name: Sauce Labs
on: push
jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      # To not exceed Sauce Labs concurrency limit
      max-parallel: 1
      fail-fast: false
      matrix:
        node: [10, 12, 14]
    name: Node ${{ matrix.node }}
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Use node ${{ matrix.node }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node }}
      - name: Install
        run: npm install
        env:
          # Download Sauce Connect binary now instead of on first run
          SAUCE_CONNECT_DOWNLOAD_ON_INSTALL: true
      - name: Add host
        run: echo "127.0.0.1 airtap.local" | sudo tee -a /etc/hosts
      - name: Test
        run: npm run test:integration
        env:
          SAUCE_USERNAME: ${{ secrets.SAUCE_USERNAME }}
          SAUCE_ACCESS_KEY: ${{ secrets.SAUCE_ACCESS_KEY }}
          DEBUG_COLORS: true
